version: '3.1'

services:

  db:
    image: muritiku/postgres-tds
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080